#ifndef _FRONTEND_DEFS_HPP
#define _FRONTEND_DEFS_HPP

#define FILENAME_BUFFER_SIZE 260
#define ERROR_BUFFER_SIZE 500
#define REGULAR_BUFFER_SIZE 1024

#define GLOBAL_THREAD_LIMITATION 20

#define DEFAULT_PORT 3040
#define PROTOCOL_TCP 0
#define SOCKET_LISTENING_QUEUE_LENGTH 10

#define SERVER_IP "127.0.0.1"

#define throws(error_name)

#endif
