#ifndef _BACKEND_DEFS_HPP
#define _BACKEND_DEFS_HPP

enum class ThreadStatCode
{
    SUCCESS,
    FILE_NOT_FOUND,
    PIPE_CREATE_FAILED,
    REDIRECT_FAILED,
    FORK_FAILED,
    CLIENT_COMMAND_ERROR,
    INVALID_ARGUMENT,
    PROCESS_SIGNALED,
    COMPILE_FAILED,
    WAITPID_FAILED,
    ALLOCATION_FAILED,
    STREAM_READ_ERROR,
    EXEC_FAILED,
    EXECUTION_FAILED,
    UNKNOWN_ERROR,
};

#define FILENAME_BUFFER_SIZE 260
#define ERROR_BUFFER_SIZE 500
#define REGULAR_BUFFER_SIZE 1024

#define GLOBAL_THREAD_LIMITATION 20

#define DEFAULT_PORT 3040
#define PROTOCOL_TCP 0
#define SOCKET_LISTENING_QUEUE_LENGTH 10

#define SERVER_IP "127.0.0.1"

#define throws(error_name)

#define LOG_DIRECTORY "cpl-log"
#define OUT_DIRECTORY "out"

#endif
